new Milk(new Cinnamon(new Tea())).value()
new Cream(new Sugar(new Coffee()))
new Cream(new Sugar(new Coffee())).value()
new Cinnamon(new Milk(new Cream(new Sugar(new Coffee()))))
new Cinnamon(new Milk(new Cream(new Sugar(new Coffee())))).value()
new Milk(new Cinnamon(new Tea())).prep()
new Cinnamon(new Milk(new Tea())).prep()
new Cinnamon(new Milk(new Cream(new Sugar(new Coffee())))).prep()
new Cream(new Milk(new Cinnamon(new Sugar(new Coffee())))).prep()