new Nutri("fat", 1).update("sugar", 2).update("caffeine", 3).update("sugar",4)
new Milk(new Coffee())
new Milk(new Coffee()).value()
Drink drink = new Milk(new Tea())
drink.value()
new Sugar(new Milk(new Coffee()))
new Sugar(new Milk(new Coffee())).value()
new Milk(new Sugar(new Tea()))
new Milk(new Sugar(new Tea())).value()