new Point(1.0, 1.0).toStr().map(x -> "$0 ==> " + x).print()
new Point(1.0, 1.0).toStr().flatMap(x -> Str.of("$0 ==> ").map(y -> y + x)).run(x -> System.out.println(x))
System.out.println("Error expected below:")
new Point(1.0, 1.0).toStr().map(x -> x.length())
new Point(1.0, 1.0).toStr().join("...").print()
new Point(1.0, 1.0).toStr().join(Str.of("...")).run(x -> System.out.println(x))
new Point(1.0, 1.0).toStr().join(new Point(2.0, 2.0).toStr()).print()
new Circle(new Point(0.0, 0.0), 1.0)
new Circle(new Point(0.0, 0.0), 1.0).toStr().run(x -> System.out.println(x))