ack(1, 2)
new FuncStat()
Pair<Integer, FuncStat> result = ack(1, 2).accept(new FuncStat())
System.out.println("--- extra test cases added by the contributor :D ---")
System.out.println("ack(1, 0): expected - (2, count=2 maxDepth=2), output - ")
Pair<Integer, FuncStat> result = ack(1, 0).accept(new FuncStat())
System.out.println("ack(4, 0): expected - (13, count=107 maxDepth=16), output - ")
Pair<Integer, FuncStat> result = ack(4, 0).accept(new FuncStat())
System.out.println("ack(3, 2): expected - (29, count=541 maxDepth=31), output - ")
Pair<Integer, FuncStat> result = ack(3, 2).accept(new FuncStat())