Fraction.of(1, 2).add(Fraction.of(1, 4))
Fraction.of(-1, 2).add(Fraction.of(1, 4))
Fraction.of(1, 2).sub(Fraction.of(1, 4))
Fraction.of(1, 4).sub(Fraction.of(1, 2))
Fraction.of(1, 2).mul(Fraction.of(2, 1))
Fraction.of(1, 2).mul(Fraction.of(2, 0))