Main.reverse("orange").equals("egnaro")
Main.reverse("one two three").equals("eerht owt eno")
Main.reverse("").equals("")
Main.reverse("the quick brown fox jumps over the lazy dog.")
Main.reverse("the quick brown fox jumps over the lazy dog.").equals(".god yzal eht revo spmuj xof nworb kciuq eht")
